# playbooks/lab7/playbook.yml
---
- name: Configure nginx
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Change nginx configuration
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^worker_processes'
        line: 'worker_processes 4;'
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
