# playbooks/lab2/debug-playbook.yml
---
- name: Debug playbook variables
  hosts: managed_nodes
  gather_facts: yes

  tasks:
    - name: Display all variables for the host
      debug:
        var: hostvars[inventory_hostname]

    - name: Display specific facts
      debug:
        msg: |
          Hostname: {{ ansible_hostname }}
          IP Address: {{ ansible_default_ipv4.address }}
          OS: {{ ansible_distribution }}
