---
- name: Install database packages
  package:
    name: "{{ database_packages }}"
    state: present

- name: Start and enable database service
  service:
    name: "{{ database_service }}"
    state: started
    enabled: yes

- name: Configure database
  template:
    src: "{{ database_config_template }}"
    dest: "{{ database_config_path }}"
    backup: yes
  notify: restart database

- name: Create application database
  mysql_db:
    name: "{{ app_database_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  when: database_type == "mysql"

- name: Create database user
  mysql_user:
    name: "{{ app_database_user }}"
    password: "{{ app_database_password }}"
    priv: "{{ app_database_name }}.*:ALL"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  when: database_type == "mysql"
