---
- name: Install monitoring tools
  apt:
    name:
      - htop
      - iotop
    state: present
    update_cache: yes

- name: Create monitoring script
  template:
    src: db-monitor.sh.j2
    dest: /usr/local/bin/db-monitor.sh
    mode: '0755'
